apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: ootoya
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        - configMapRef:
            name: feature-toggle
        name: app-deployment
        image: harbor.dev.afsmtddso.com/ootoya-harbor-project/app@sha256:4111dd2a4745cdf0fc79c9e26049c4f7fc8c1126083ed717bb05a10af4087106
        ports:
        - containerPort: 5000
